{
 "title": "LLM benchmark",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Decoding benchmark\n\nShareGPT: 1000 prompts randomly sampled from `ShareGPT` dataset with fixed random seed."
   },
   "targets": [
    {
     "expr": "load_genenerator:total_request_count_total{dataset=\"sharegpt\"}",
     "legendFormat": "Total requests"
    },
    {
     "expr": "load_genenerator:successful_request_count_total{dataset=\"sharegpt\"}",
     "legendFormat": "Successful requests"
    },
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "# Pre-fill benchmark\n\n1000 prompts synthetically generated from `sonnet.txt` dataset with roughly 460 input tokens and 16 output tokens on average"
   },
   "targets": [
    {
     "expr": "load_genenerator:total_request_count_total{dataset=\"sharegpt\"}",
     "legendFormat": "Total requests"
    },
    {
     "expr": "load_genenerator:successful_request_count_total{dataset=\"sharegpt\"}",
     "legendFormat": "Successful requests"
    },
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(load_genenerator:total_request_count_total{dataset=\"sharegpt\"})",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum(load_genenerator:successful_request_count_total{dataset=\"sharegpt\"})",
     "legendFormat": "Successful requests"
    },
    {
     "expr": "sum(load_genenerator:failed_request_count_total{dataset=\"sharegpt\"})",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(load_genenerator:total_request_count_total{dataset=\"sonnet\"})",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum(load_genenerator:successful_request_count_total{dataset=\"sonnet\"})",
     "legendFormat": "Successful requests"
    },
    {
     "expr": "sum(load_genenerator:failed_request_count_total{dataset=\"sonnet\"})",
     "legendFormat": "Failed requests"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(load_genenerator:request_throughput{dataset=\"sharegpt\"})",
     "legendFormat": "Requests /s"
    },
    {
     "expr": "avg(load_genenerator:output_token_throughput{dataset=\"sharegpt\"})",
     "legendFormat": "Output Tokens /s"
    },
    {
     "expr": "avg(load_genenerator:total_token_throughput{dataset=\"sharegpt\"})",
     "legendFormat": "Total Tokens /s"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(load_genenerator:request_throughput{dataset=\"sonnet\"})",
     "legendFormat": "Requests /s"
    },
    {
     "expr": "avg(load_genenerator:output_token_throughput{dataset=\"sonnet\"})",
     "legendFormat": "Output Tokens /s"
    },
    {
     "expr": "avg(load_genenerator:total_token_throughput{dataset=\"sonnet\"})",
     "legendFormat": "Total Tokens /s"
    }
   ]
  },
  { "title": "Time to First Token (TTFT)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Time to First Token (TTFT)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(load_genenerator:ttft_mean{dataset=\"sharegpt\"})",
     "legendFormat": "TTFT mean"
    },
    {
     "expr": "avg(load_genenerator:ttft_median{dataset=\"sharegpt\"})",
     "legendFormat": "TTFT median"
    },
    {
     "expr": "avg(load_genenerator:ttft_p99{dataset=\"sharegpt\"})",
     "legendFormat": "TTFT p99"
    }
   ]
  },
  {
   "title": "Time to First Token (TTFT)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(load_genenerator:ttft_mean{dataset=\"sonnet\"})",
     "legendFormat": "TTFT mean"
    },
    {
     "expr": "avg(load_genenerator:ttft_median{dataset=\"sonnet\"})",
     "legendFormat": "TTFT median"
    },
    {
     "expr": "avg(load_genenerator:ttft_p99{dataset=\"sonnet\"})",
     "legendFormat": "TTFT p99"
    }
   ]
  },
  {
   "title": "Time to First Token (TTFT)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(le) (load_generator:ttft_bucket{dataset=\"sharegpt\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time to First Token (TTFT)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(le) (load_generator:ttft_bucket{dataset=\"sonnet\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Time per Output Token (TPOT)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Time per Output Token (TPOT)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(load_genenerator:tpot_mean{dataset=\"sharegpt\"})",
     "legendFormat": "TPOT mean"
    },
    {
     "expr": "avg(load_genenerator:tpot_median{dataset=\"sharegpt\"})",
     "legendFormat": "TPOT median"
    },
    {
     "expr": "avg(load_genenerator:tpot_p99{dataset=\"sharegpt\"})",
     "legendFormat": "TPOT p99"
    }
   ]
  },
  {
   "title": "Time per Output Token (TPOT)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(load_genenerator:tpot_mean{dataset=\"sonnet\"})",
     "legendFormat": "TPOT mean"
    },
    {
     "expr": "avg(load_genenerator:tpot_median{dataset=\"sonnet\"})",
     "legendFormat": "TPOT median"
    },
    {
     "expr": "avg(load_genenerator:tpot_p99{dataset=\"sonnet\"})",
     "legendFormat": "TPOT p99"
    }
   ]
  },
  {
   "title": "Time per Output Token (TPOT)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(le) (load_generator:tpot_bucket{dataset=\"sharegpt\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time per Output Token (TPOT)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(le) (load_generator:tpot_bucket{dataset=\"sonnet\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Inter Token Latency (ITL, per token)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }
  },
  {
   "title": "Inter-Token Latency (ITL)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(load_genenerator:itl_mean{dataset=\"sharegpt\"})",
     "legendFormat": "ITL mean"
    },
    {
     "expr": "avg(load_genenerator:itl_median{dataset=\"sharegpt\"})",
     "legendFormat": "ITL median"
    },
    {
     "expr": "avg(load_genenerator:itl_p99{dataset=\"sharegpt\"})",
     "legendFormat": "ITL p99"
    }
   ]
  },
  {
   "title": "Inter-Token Latency (ITL)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(load_genenerator:itl_mean{dataset=\"sonnet\"})",
     "legendFormat": "ITL mean"
    },
    {
     "expr": "avg(load_genenerator:itl_median{dataset=\"sonnet\"})",
     "legendFormat": "ITL median"
    },
    {
     "expr": "avg(load_genenerator:itl_p99{dataset=\"sonnet\"})",
     "legendFormat": "ITL p99"
    }
   ]
  },
  {
   "title": "Inter-Token Latency (ITL)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(le) (load_generator:itl_bucket{dataset=\"sharegpt\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Inter-Token Latency (ITL)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(le) (load_generator:itl_bucket{dataset=\"sonnet\"})",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}