{{- if .Values.hfToken -}}
# Must be managed outside of helm
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: hf-secret
stringData:
  hfToken: "{{ .Values.hfToken }}"
{{- end -}}
