apiVersion: v1
kind: Service
metadata:
  name: {{ include "inference-benchmark-backend.fullname" . }}
  labels:
    {{- include "inference-benchmark-backend.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app:  {{ include "inference-benchmark-backend.fullname" . }}
