apiVersion: v1
kind: Service
metadata:
  name: {{ include "inference-benchmark-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "inference-benchmark-backend.fullname" .  }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - name: workers
      port: 6379
  clusterIP: None
  selector:
    app: {{ include "inference-benchmark-backend.fullname" .  }}
